package com.aaris.quran;

import android.content.Context;
import com.aaris.quran.core.MeaningSearch;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONObject;
import org.json.JSONArray;
import java.io.*;
import java.util.*;

/** Complete ayah translations; never assembled from word glosses or generated by a model. */
final class TranslationStore implements AutoCloseable {
    static final class Edition {
        final String id,language,title,description,version,source;
        Edition(Cursor c){id=c.getString(0);language=c.getString(1);title=c.getString(2);description=c.getString(3);version=c.getString(4);source=c.getString(5);}
        String attribution(){
            String lower=source==null?"":source.toLowerCase(Locale.ROOT);
            String publisher=lower.contains("quranenc")?"QuranEnc.com":lower.contains("tanzil")?"Tanzil Project":source;
            return title+" · v"+version+(publisher==null||publisher.trim().isEmpty()?"":" · "+publisher);
        }
    }
    static final class Entry {
        final Edition edition;final String text,footnotes;
        Entry(Edition edition,String text,String footnotes){this.edition=edition;this.text=text;this.footnotes=footnotes;}
    }
    final List<Edition> editions=new ArrayList<>();final String packHash,notice;
    private static final int ENTRY_CACHE_LIMIT=512;
    private final Map<String,Entry> entryCache=Collections.synchronizedMap(new LinkedHashMap<String,Entry>(ENTRY_CACHE_LIMIT,.75f,true){
        @Override protected boolean removeEldestEntry(Map.Entry<String,TranslationStore.Entry> eldest){return size()>ENTRY_CACHE_LIMIT;}
    });
    private final SQLiteDatabase db;
    TranslationStore(Context c)throws Exception{
        JSONObject manifest=new JSONObject(ContentStore.asset(c,"translations-manifest.json"));packHash=manifest.getString("sqlite_sha256");notice=manifest.getString("notice");
        JSONArray expectedEditions=manifest.getJSONArray("editions");
        if(manifest.optInt("schema",-1)!=1||expectedEditions.length()<1||!packHash.matches("[a-f0-9]{64}"))throw new IOException("Invalid translation pack identity");
        File target=new File(c.getFilesDir(),"translations-"+packHash.substring(0,16)+".sqlite");
        if(!target.isFile()||!ContentStore.hash(target).equals(packHash)){
            File temp=new File(c.getFilesDir(),"translations.installing");
            try(InputStream in=c.getAssets().open("translations.sqlite");FileOutputStream out=new FileOutputStream(temp)){byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1)out.write(b,0,n);out.getFD().sync();}
            if(!ContentStore.hash(temp).equals(packHash)){temp.delete();throw new IOException("Translation checksum mismatch");}
            if(target.exists()&&!target.delete())throw new IOException("Could not replace translation pack");
            if(!temp.renameTo(target))throw new IOException("Translation install failed");
        }
        SQLiteDatabase opened=SQLiteDatabase.openDatabase(target.getAbsolutePath(),null,SQLiteDatabase.OPEN_READONLY);
        try{
            try(Cursor cur=opened.rawQuery("PRAGMA quick_check",null)){if(!cur.moveToFirst()||!"ok".equals(cur.getString(0)))throw new IOException("Translation integrity check failed");}
            if(!columns(opened,"edition").equals(new LinkedHashSet<>(Arrays.asList("id","language","title","description","version","source")))||
                !columns(opened,"translation").equals(new LinkedHashSet<>(Arrays.asList("edition_id","ayah_id","text","footnotes"))))
                throw new IOException("Translation schema mismatch");
            try(Cursor cur=opened.rawQuery("SELECT count(*) FROM translation t LEFT JOIN edition e ON e.id=t.edition_id WHERE e.id IS NULL",null)){
                if(!cur.moveToFirst()||cur.getInt(0)!=0)throw new IOException("Translation pack contains orphan rows");
            }
            try(Cursor cur=opened.rawQuery("SELECT * FROM edition ORDER BY CASE language WHEN 'hi' THEN 0 WHEN 'ur' THEN 1 ELSE 2 END,rowid",null)){while(cur.moveToNext())editions.add(new Edition(cur));}
            LinkedHashSet<String> expected=new LinkedHashSet<>();for(int i=0;i<expectedEditions.length();i++)expected.add(expectedEditions.getString(i));
            if(expected.size()!=expectedEditions.length())throw new IOException("Duplicate translation edition in manifest");
            LinkedHashSet<String> actual=new LinkedHashSet<>();for(Edition edition:editions){
                if(edition.id==null||edition.id.trim().isEmpty()||edition.language==null||edition.language.trim().isEmpty()||edition.title==null||edition.title.trim().isEmpty()||edition.version==null||edition.version.trim().isEmpty())
                    throw new IOException("Incomplete translation edition metadata");
                actual.add(edition.id);
            }
            if(!actual.equals(expected))throw new IOException("Translation editions do not match the manifest");
            for(Edition edition:editions)try(Cursor cur=opened.rawQuery("SELECT count(*),count(DISTINCT ayah_id) FROM translation WHERE edition_id=? AND text IS NOT NULL AND trim(text)<>''",new String[]{edition.id})){
                if(!cur.moveToFirst()||cur.getInt(0)!=6236||cur.getInt(1)!=6236)throw new IOException("Incomplete translation edition: "+edition.id);
            }
            try(Cursor cur=opened.rawQuery("SELECT count(DISTINCT ayah_id) FROM translation",null)){if(!cur.moveToFirst()||cur.getInt(0)!=6236)throw new IOException("Translation coordinate coverage mismatch");}
            try(Cursor cur=opened.rawQuery("SELECT count(*) FROM translation",null)){if(!cur.moveToFirst()||cur.getInt(0)!=6236*expected.size())throw new IOException("Unexpected translation row count");}
        }catch(Exception invalid){opened.close();throw invalid;}
        db=opened;
        File[] old=c.getFilesDir().listFiles();
        if(old!=null)for(File file:old)if(file.isFile()&&file.getName().startsWith("translations-")&&
            file.getName().endsWith(".sqlite")&&!file.equals(target))file.delete();
    }
    Edition edition(String id){for(Edition e:editions)if(e.id.equals(id))return e;return null;}
    Edition preferredEdition(String id,String language){
        Edition exact=edition(id);if(exact!=null)return exact;
        if(language!=null)for(Edition e:editions)if(language.equals(e.language))return e;
        return editions.isEmpty()?null:editions.get(0);
    }
    private static LinkedHashSet<String> columns(SQLiteDatabase db,String table){LinkedHashSet<String> result=new LinkedHashSet<>();try(Cursor c=db.rawQuery("PRAGMA table_info("+table+")",null)){while(c.moveToNext())result.add(c.getString(1));}return result;}
    private static String cacheKey(String editionId,String ayahId){return editionId+"\n"+ayahId;}
    Entry get(String editionId,String ayahId){
        Edition edition=edition(editionId);if(edition==null||ayahId==null)return null;
        String key=cacheKey(edition.id,ayahId);Entry cached=entryCache.get(key);if(cached!=null)return cached;
        try(Cursor c=db.rawQuery("SELECT text,footnotes FROM translation WHERE edition_id=? AND ayah_id=?",new String[]{edition.id,ayahId})){
            if(!c.moveToFirst())return null;Entry value=new Entry(edition,c.getString(0),c.getString(1));entryCache.put(key,value);return value;
        }
    }
    Map<String,Entry> get(String editionId,Collection<String> ayahIds){
        LinkedHashMap<String,Entry> out=new LinkedHashMap<>();Edition edition=edition(editionId);
        if(edition==null||ayahIds==null||ayahIds.isEmpty())return out;
        LinkedHashSet<String> unique=new LinkedHashSet<>();for(String id:ayahIds)if(id!=null&&!id.isEmpty())unique.add(id);
        if(unique.isEmpty())return out;
        List<String> missing=new ArrayList<>();
        for(String id:unique){Entry cached=entryCache.get(cacheKey(edition.id,id));if(cached!=null)out.put(id,cached);else missing.add(id);}
        if(missing.isEmpty())return out;
        List<String> args=new ArrayList<>();args.add(edition.id);args.addAll(missing);
        String marks=String.join(",",Collections.nCopies(missing.size(),"?"));
        try(Cursor c=db.rawQuery("SELECT ayah_id,text,footnotes FROM translation WHERE edition_id=? AND ayah_id IN ("+marks+")",args.toArray(new String[0]))){
            while(c.moveToNext()){
                String id=c.getString(0);Entry value=new Entry(edition,c.getString(1),c.getString(2));entryCache.put(cacheKey(edition.id,id),value);out.put(id,value);
            }
        }
        return out;
    }
    Map<String,String> searchText(){
        Map<String,StringBuilder> builders=new HashMap<>();
        try(Cursor c=db.rawQuery(
            "SELECT t.ayah_id,t.text,e.language FROM translation t JOIN edition e ON e.id=t.edition_id ORDER BY t.edition_id,t.ayah_id",null)){
            while(c.moveToNext()){
                String ayahId=c.getString(0),text=c.getString(1),language=c.getString(2);
                StringBuilder out=builders.computeIfAbsent(ayahId,k->new StringBuilder());
                out.append(text).append(' ');
                // Search-only Hinglish shadow. The displayed translation remains the exact archived source.
                if("hi".equals(language)){
                    String roman=MeaningSearch.romanizeHindi(text);
                    if(!roman.isEmpty())out.append(roman).append(' ');
                }
            }
        }
        Map<String,String> result=new HashMap<>();
        for(Map.Entry<String,StringBuilder> e:builders.entrySet())result.put(e.getKey(),e.getValue().toString());
        return result;
    }
    public void close(){db.close();}
}
