package com.aaris.quran;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONObject;
import java.io.*;
import java.util.*;

/** Complete ayah translations; never assembled from word glosses or generated by a model. */
final class TranslationStore implements AutoCloseable {
    static final class Edition {
        final String id,language,title,description,version,source;
        Edition(Cursor c){id=c.getString(0);language=c.getString(1);title=c.getString(2);description=c.getString(3);version=c.getString(4);source=c.getString(5);}
        String attribution(){return title+" · v"+version+" · QuranEnc.com";}
    }
    static final class Entry {
        final Edition edition;final String text,footnotes;
        Entry(Edition edition,String text,String footnotes){this.edition=edition;this.text=text;this.footnotes=footnotes;}
    }
    final List<Edition> editions=new ArrayList<>();final String packHash,notice;
    private final SQLiteDatabase db;
    TranslationStore(Context c)throws Exception{
        JSONObject manifest=new JSONObject(ContentStore.asset(c,"translations-manifest.json"));packHash=manifest.getString("sqlite_sha256");notice=manifest.getString("notice");
        if(!packHash.matches("[a-f0-9]{64}"))throw new IOException("Invalid translation pack hash");
        File target=new File(c.getFilesDir(),"translations-"+packHash.substring(0,16)+".sqlite");
        if(!target.isFile()||!ContentStore.hash(target).equals(packHash)){
            File temp=new File(c.getFilesDir(),"translations.installing");
            try(InputStream in=c.getAssets().open("translations.sqlite");FileOutputStream out=new FileOutputStream(temp)){byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1)out.write(b,0,n);out.getFD().sync();}
            if(!ContentStore.hash(temp).equals(packHash)){temp.delete();throw new IOException("Translation checksum mismatch");}
            if(target.exists()&&!target.delete())throw new IOException("Could not replace translation pack");
            if(!temp.renameTo(target))throw new IOException("Translation install failed");
        }
        db=SQLiteDatabase.openDatabase(target.getAbsolutePath(),null,SQLiteDatabase.OPEN_READONLY);
        try(Cursor cur=db.rawQuery("SELECT * FROM edition ORDER BY CASE language WHEN 'hi' THEN 0 WHEN 'ur' THEN 1 ELSE 2 END",null)){while(cur.moveToNext())editions.add(new Edition(cur));}
    }
    Edition edition(String id){for(Edition e:editions)if(e.id.equals(id))return e;return editions.isEmpty()?null:editions.get(0);}
    Entry get(String editionId,String ayahId){Edition edition=edition(editionId);if(edition==null)return null;try(Cursor c=db.rawQuery("SELECT text,footnotes FROM translation WHERE edition_id=? AND ayah_id=?",new String[]{edition.id,ayahId})){return c.moveToFirst()?new Entry(edition,c.getString(0),c.getString(1)):null;}}
    Map<String,String> searchText(){Map<String,StringBuilder> builders=new HashMap<>();try(Cursor c=db.rawQuery("SELECT ayah_id,text FROM translation ORDER BY edition_id,ayah_id",null)){while(c.moveToNext())builders.computeIfAbsent(c.getString(0),k->new StringBuilder()).append(c.getString(1)).append(' ');}Map<String,String> result=new HashMap<>();for(Map.Entry<String,StringBuilder> e:builders.entrySet())result.put(e.getKey(),e.getValue().toString());return result;}
    public void close(){db.close();}
}
