plugins { id 'java-library' }
java { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 }
tasks.register('coreCheck', JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.aaris.quran.core.CoreChecks'
    workingDir rootProject.projectDir
}
