plugins { id 'com.android.application' }
android {
    namespace 'com.aaris.quran'
    compileSdk 35
    defaultConfig {
        applicationId 'com.aaris.quran'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { release { minifyEnabled false } }
}
dependencies { implementation project(':core') }
